### ISSUE TITLE
Cannot get binlog info from MariaDB 10.2.x when string length greater than 252

### ISSUE THREAD

**Issue by mia0x75** [go-mysql-org/go-mysql#204]
MariaDB 10.2.11 w/ CentOS 7.4, go-canal latest git version

table schema:
```
CREATE TABLE `dt_text` (
  `c` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

when string value length less than or equals 252, everything is ok
```
insert into dt_text values (repeat('1', 252));
```

and when length greater than 252, go-canal does not print any information.
```
insert into dt_text values (repeat('1', 252));
insert into dt_text values (repeat('1', 253));
insert into dt_text values (repeat('1', 65535));
```

**Comment by siddontang** [comment]
@mia0x75 

Can you show me the output information? does go-canal panic?

**Comment by mia0x75** [comment]
Hi @siddontang,

go-canal is still running, and it prints nothing, it just missing this binlog info.

**Comment by siddontang** [comment]
How about

```
insert into dt_text values (repeat('1', 252));
insert into dt_text values (repeat('1', 253));
insert into dt_text values (repeat('1', 65535));
insert into dt_text values (repeat('1', 252));
```

>  it just missing this binlog info

What is the mean here?

**Comment by mia0x75** [comment]
I cannot see any output on go-canal, looks like go-canal miss it.

**Comment by siddontang** [comment]
can you show me the canel output? I am confused what do you say.

**Comment by mia0x75** [comment]
screen dump attached, thx.
![screenshot from 2017-12-11 20-00-53-min](https://user-images.githubusercontent.com/5111356/33831056-78f6a90e-deb1-11e7-94a8-85a0fab3299d.png)

**Comment by siddontang** [comment]
seem this is not the canal output, do you add the info log by yourself?

**Comment by mia0x75** [comment]
no, just git clone and compile.

**Comment by siddontang** [comment]
Do you try `insert into dt_text values (repeat('1', 252));` again?

**Comment by mia0x75** [comment]
it's the same, you can easy to install mariadb to verify.

**Comment by mia0x75** [comment]
Finally, I find the root cause, the issue caused by new system variables in MariaDB 10.2

log_bin_compress & log_bin_compress_min_len

Thus, go-canal cannot process compressed bin log.

**Comment by siddontang** [comment]
got it @mia0x75 

We have not supported the compression yet. You can help us add this if possible.
