### ISSUE TITLE
dump don't work anymore "exit status 7?"

### ISSUE THREAD

**Issue by remotejob** [go-mysql-org/go-mysql#264]
After last update "canal/dump" don't work anymore :(

`time="2018-04-30T04:45:43Z" level=info msg="try dump MySQL and parse" `

`exit status 7 `???

**Comment by remotejob** [comment]
Ok. I find issue it's mysqdump from mariadb don't work. 

In my case I use docker alpine small image instead of complete ubuntu:16.04  but package mysql-client created from mariadb! (default now)

`RUN apk add --no-cache --virtual mysql-client` 

It will be nice to have option use as well mysqdump from mariaDB.

Thanks.

**Comment by siddontang** [comment]
Hi @remotejob 

Do you mean if you use MariaDB mysqldump, it can't work with MySQL?

**Comment by remotejob** [comment]
Yes. Probably it's not issue at all?

**Comment by siddontang** [comment]
can we use MySQL mysqldump for MariaDB? If yes, we can change it.

**Comment by remotejob** [comment]
I only test  mysqldump(mariadb)  -----> MYSQL for me it don't work. 

I don't test mysqldump(mysql)  -------> MariaDB

**Comment by siddontang** [comment]
maybe we should support two Dockerfiles, one is for MySQL mysqldump, and the other is for MariaDB.

**Comment by remotejob** [comment]
If take in consideration mysqldump have the same name as for mysql as well for Mariadb.

I will do:

cfg.Dump.ExecutionPath = "mysqldump"

cfg.Dump.DbKind ="mysql/mariadb..."

But It's up to you.

**Comment by siddontang** [comment]
In the replication mode, there is a Flavor configuration, using it we can send different commands for MySQL/MariaDB, but for mysqldump, nearly they use the same flags, hard to distinguish. 

Maybe we can add a comment in the dump for this error.
