### ISSUE TITLE
看到一个注释

### ISSUE THREAD

**Issue by molizz** [go-mysql-org/go-mysql#463]
https://github.com/siddontang/go-mysql/blob/fba9c9655f7cff606e91f387352561ec5a77de4b/replication/binlogsyncer.go#L715

这里看到作者的注释是不知道为什么会读取到 EOF.

我这边的情况是，当mysqld进程关闭的时候，会读取到EOF。

大概是因为 关闭mysql进程后，会创建新的binlog文件（例如之前是 mysql-001, 重启mysql进程后，001就不在有效，会创建一个新的 002）。

不确定是否是这个原因。

希望有帮助。

**Comment by siddontang** [comment]
thanks @molizz 

but seems that other scenarios can still meet this, and I don't know why too.
