### ISSUE TITLE
 Access denied for user 'root'@'127.0.0.1:3306' (using password: Yes) 

### ISSUE THREAD

**Issue by xhrg** [go-mysql-org/go-mysql#531]
1. 基于go-mysql v1.1.0
2. mysql-connetor

java代码：
DriverManager.getConnection("jdbc:mysql://127.0.0.1:33060/ssdb?verifyServerCertificate=false&useSSL=false", "root", "root");

golang代码

`
func main() {
	logrus.SetLevel(logrus.DebugLevel)
	l, _ := net.Listen("tcp", ":33060")
	for true {
		c, error := l.Accept()
		if error != nil {
			logrus.Errorf("accept error, %v", error)
		}
		conn, error := server.NewConn(c, "root", "root", pkg.NewHandler())
		if error != nil {
			logrus.Errorf("server.NewConn error, %v", error)
			continue
		}
		go handlerConn(conn)
	}
}
`

这样会报错   Access denied for user 'root'@'127.0.0.1:3306' (using password: Yes)

**Comment by pretty66** [comment]
嗨，你这个问题解决了吗，我遇到了同样的问题！
