### ISSUE TITLE
go mod tidy 失败

### ISSUE THREAD

**Issue by chowyu08** [go-mysql-org/go-mysql#558]
go: found gopkg.in/check.v1 in gopkg.in/check.v1 v1.0.0-20201130134442-10cb98267c6c
go: finding module for package github.com/juju/errors
go: finding module for package github.com/cznic/mathutil
go: finding module for package github.com/pingcap/tidb/types/parser_driver
go: found github.com/cznic/mathutil in github.com/cznic/mathutil v0.0.0-20181122101859-297441e03548
go: found github.com/juju/errors in github.com/juju/errors v0.0.0-20200330140219-3fe23663418f
go: finding module for package github.com/remyoudompheng/bigfft
go: finding module for package github.com/pingcap/tidb/types/parser_driver
go: found github.com/remyoudompheng/bigfft in github.com/remyoudompheng/bigfft v0.0.0-20200410134404-eec4a21b6bb0
go: finding module for package github.com/pingcap/tidb/types/parser_driver
canal imports
        github.com/siddontang/go-mysql/canal imports
        github.com/pingcap/parser tested by
        github.com/pingcap/parser.test imports
        github.com/pingcap/tidb/types/parser_driver: module github.com/pingcap/tidb@latest found (v2.0.11+incompatible), but does not contain package github.com/pingcap/tidb/types/parser_driver

**Comment by atercattus** [comment]
Hello.
Fixed at https://github.com/go-mysql-org/go-mysql/pull/559
