### ISSUE TITLE
Try install and get the error

### ISSUE THREAD

**Issue by romani-dev** [go-mysql-org/go-mysql#567]
hi!

### go.mod
```
module github.com/my/project

go 1.15

require github.com/go-mysql-org/go-mysql v1.1.1
```

So i run <code><b>go mod tidy</b></code> and receive the follow error:

```
go: github.com/go-mysql-org/go-mysql@v1.1.1: parsing go.mod:
        module declares its path as: github.com/siddontang/go-mysql
                but was required as: github.com/go-mysql-org/go-mysql
```

**Comment by lance6716** [comment]
We renamed the repo some days ago. Could you help us fix this error?

**Comment by atercattus** [comment]
It seems we need to change our imports to a new project path (with a new semver tag).

We can still use `require github.com/siddontang/go-mysql` in all go.mods, but for `require github.com/go-mysql-org/go-mysql` I cannot find any working solution.

**Comment by lance6716** [comment]
Now I could run the [example in README](https://github.com/go-mysql-org/go-mysql#canal) with following go.mod

```
module github.com/my/project

go 1.15

require (
	github.com/go-mysql-org/go-mysql master
)
```
