### ISSUE TITLE
invalid interval format

### ISSUE THREAD

**Issue by zr-hebo** [go-mysql-org/go-mysql#606]
线上使用 go-mysql拉 binlog，偶尔会出现正常的 GTID连接报异常的情况。下面是一段错误日志：
```
stream.go:34] dump MySQL stream at 'b280eaf0-593b-11ea-8de7-246e96a11940:1-6634997792' failed <-- invalid interval format, must n[-n] and the end must >= start
```
任务失败后重启错误消失，不知道有没有朋友遇到过同样的问题。

**Comment by zenghuasheng** [comment]
举手，朋友，你查到是什么原因吗？
`[ERROR] 2023-03-17 16:47:04 etl/runner.go:398 rule group department fetch message error: invalid GTID event: {"action":"GTID","database":"","pos":{"part":"mysql-bin.000161","offset":442551969},"table":"","values":"(1679034678,'1d8aa170-4bab-11ed-ab0b-fe81b7898041:77343763','1d8aa170-4bab-11ed-ab0b-fe81b7898041:1-77343764:1513209814434447438-369099236,c6156288-4baa-11ed-b02d-fa9d442e175e:1-79559687')"}: invalid interval format, must n[-n] and the end must >= start
`

> 线上使用 go-mysql拉 binlog，偶尔会出现正常的 GTID连接报异常的情况。下面是一段错误日志：
> 
> ```
> stream.go:34] dump MySQL stream at 'b280eaf0-593b-11ea-8de7-246e96a11940:1-6634997792' failed <-- invalid interval format, must n[-n] and the end must >= start
> ```
> 
> 任务失败后重启错误消失，不知道有没有朋友遇到过同样的问题。
