### ISSUE TITLE
ERROR 2027 (HY000): Malformed packet

### ISSUE THREAD

**Issue by GarrettQi** [go-mysql-org/go-mysql#618]
Server version: 5.7.32-log MySQL Community Server (GPL)
执行show slave hosts；mysql版本5.7.32遇到下列报错，mysql版本5.7.20可以正常运行

root@mysqldb 15:54:40 [(none)]> show slave hosts;
ERROR 2027 (HY000): Malformed packet

**Comment by lance6716** [comment]
suspecting I use the wrong MySQL version so this issue is not fixed 😂

**Comment by lance6716** [comment]
not fixed, see https://github.com/pingcap/ticdc/issues/3419#issuecomment-996431072

**Comment by atercattus** [comment]
We need more tests for that 😔
