### ISSUE TITLE
canal newValueExpr assignment error

### ISSUE THREAD

**Issue by zqueenlyl** [go-mysql-org/go-mysql#620]
/pkg/mod/github.com/go-mysql-org/go-mysql@v1.3.0/canal/expr.go:11:19: cannot use newValueExpr (type func(interface {}, string, string) ast.ValueExpr) as type func(interface {}) ast.ValueExpr in assignment

赋值错误？

**Comment by lance6716** [comment]
update the dependencies should work 🤔

**Comment by zqueenlyl** [comment]
更新了parser依赖 可以了
