### ISSUE TITLE
does replication support mysql compress protocol?

### ISSUE THREAD

**Issue by zhanghaiyang9999** [go-mysql-org/go-mysql#645]
I want to know whether the replication support the mysql compression protocol?
If yes, how to enable the compress protocol in BinlogSyncerConfig? thanks!

**Comment by lance6716** [comment]
This library can receive compressed binlog event but won't decode it. Any program using this library should implement the decoding itself. 

For example, https://github.com/pingcap/dm/issues/2192

**Comment by dveeden** [comment]
Note that there is:

- Compression in the MySQL protocol, which is used to transfer binlog events. The protocol has zlib and zstd compression. For regular MySQL to MySQL replication this is configured with `SOURCE_COMPRESSION_ALGORITHMS` as part of the `CHANGE REPLICATION SOURCE TO...` statement
- Compressed binlog events as enabled by `binlog_transaction_compression`.

- https://dev.mysql.com/doc/refman/8.0/en/change-replication-source-to.html
- https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_binlog_transaction_compression
- https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_basic_compression.html
- https://dev.mysql.com/doc/dev/mysql-server/latest/classbinary__log_1_1Transaction__payload__event.html

**Comment by dveeden** [comment]
There is already a ticket for the compressed event format: #533
