### ISSUE TITLE
decodeBlob panic

### ISSUE THREAD

**Issue by zhoukangch** [go-mysql-org/go-mysql#697]
[2022/06/09 11:46:20] [error] row_event.go:895 parse rows event panic runtime error: slice bounds out of range [:1144586244] with capacity 57, data "[\xa9\xc5\x00\x00\x00\x01\x00\a\xff\x88\xe3G\x00\x00\x00\x00\x00\x00\x00B\x1d#=\x91+\x00B\x1d#=\x91+ \x00\x00\x009D6520CEFA21BA01A0AD02CB2DFFC866\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00", parsed rows &replication.RowsEvent{Version:1, tableIDSize:6, tables:map[uint64]*replication.TableMapEvent{0xc5a95b:(*replication.TableMapEvent)(0xc111720800)}, needBitmap2:false, Table:(*replication.TableMapEvent)(0xc111720800), TableID:0xc5a95b, Flags:0x1, ExtraData:[]uint8(nil), ColumnCount:0x7, ColumnBitmap1:[]uint8{0xff}, ColumnBitmap2:[]uint8(nil), Rows:[][]interface {}{}, SkippedColumns:[][]int{}, parseTime:false, timestampStringLocation:(*time.Location)(nil), useDecimal:false, ignoreJSONDecodeErr:false}, table map &replication.TableMapEvent{flavor:"mariadb", tableIDSize:6, TableID:0xc5a95b, Flags:0x1, Schema:[]uint8{0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72}, Table:[]uint8{0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x73}, ColumnCount:0x7, ColumnType:[]uint8{0x8, 0xc, 0xc, 0xc, 0xfc, 0x8, 0x8}, ColumnMeta:[]uint16{0x0, 0x0, 0x0, 0x0, 0x4, 0x0, 0x0}, NullBitmap:[]uint8{0x7e}, SignednessBitmap:[]uint8(nil), DefaultCharset:[]uint64(nil), ColumnCharset:[]uint64(nil), SetStrValue:[][][]uint8(nil), setStrValueString:[][]string(nil), EnumStrValue:[][][]uint8(nil), enumStrValueString:[][]string(nil), ColumnName:[][]uint8(nil), columnNameString:[]string(nil), GeometryType:[]uint64(nil), PrimaryKey:[]uint64(nil), PrimaryKeyPrefix:[]uint64(nil), EnumSetDefaultCharset:[]uint64(nil), EnumSetColumnCharset:[]uint64(nil)}
goroutine 150151 [running]:
github.com/go-mysql-org/go-mysql/mysql.Pstack(...)
        /usr/local/app/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.3.0/mysql/util.go:20
github.com/go-mysql-org/go-mysql/replication.(*RowsEvent).Decode.func1(0xc0b7c76244, 0x55, 0x5c, 0xc0ea47b790, 0xc0bbabdc78)
        /usr/local/app/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.3.0/replication/row_event.go:895 +0x1b3
panic(0x18b0b40, 0xc027d21680)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/go-mysql-org/go-mysql/replication.decodeBlob(0xc0b7c76267, 0x32, 0x39, 0x16b0004, 0xc0339b1a40, 0x6, 0x0, 0x2d75d60, 0x0, 0x19fd2c29116a)
        /usr/local/app/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.3.0/replication/row_event.go:1503 +0x285
github.com/go-mysql-org/go-mysql/replication.(*RowsEvent).decodeValue(0xc0ea47b790, 0xc0b7c76267, 0x32, 0x39, 0x447fc, 0x16b7b20, 0xc0339b1a40, 0x8, 0x0, 0x0)
        /usr/local/app/go/pkg/mod/github.com/go-mysql-org/go-mysql@v1.3.0/replication/row_event.go:1133 +0x1115

**Comment by zhoukangch** [comment]
who can help me solute

**Comment by lance6716** [comment]
can you provide some steps to let us reproduce it?

**Comment by zhoukangch** [comment]
> can you provide some steps to let us reproduce it?

'/*!*/;
### INSERT INTO `png_cms_v8`.`play_tab_reco_content_intervene`
### SET
###   @1=819 /* INT meta=0 nullable=0 is_null=0 */
###   @2=2 /* INT meta=0 nullable=0 is_null=0 */
###   @3='' /* VARSTRING(2048) meta=2048 nullable=0 is_null=0 */
###   @4='11666 ä¸»æ¥¼ æ<9a><97>é»<91>æ<89><8b>æ¸¸äº®ç<9b>¸æ<9a>´é<9b>ªå<98><89>å¹´å<8d><8e>ï¼<8c>ç²¾é<9b><95>ç»<86>ç<90>¢ç<9a><84>3Aå¤§ä½<9c>' /* BLOB/TEXT meta=2 nullable=1 is_null=0 */
###   @5=2 /* INT meta=0 nullable=0 is_null=0 */
###   @6='' /* VARSTRING(2048) meta=2048 nullable=1 is_null=0 */
###   @7='116663' /* VARSTRING(2048) meta=2048 nullable=1 is_null=0 */
###   @8='54217670' /* VARSTRING(2048) meta=2048 nullable=1 is_null=0 */
###   @9='touchliu' /* VARSTRING(512) meta=512 nullable=0 is_null=0 */
###   @10=1654741895 /* TIMESTAMP meta=0 nullable=0 is_null=0 */
###   @11=1654741881 /* INT meta=0 nullable=0 is_null=0 */
###   @12=1717900273 /* INT meta=0 nullable=0 is_null=0 */
###   @13=1 /* INT meta=0 nullable=0 is_null=0 */
# at 81376240
#220609 10:31:37 server id 638346941  end_log_pos 81376267      Xid = 175000658576
COMMIT/*!*/;

**Comment by zhoukangch** [comment]
this is binlog log , decodeBlob panic

**Comment by lance6716** [comment]
I don't know how to reproduce it only from a binlog dump. Please provide informations like your MySQL (or MariaDB?) version, table structure, etc. And it's better you do reproduce it based on your information.

**Comment by zhoukangch** [comment]
mariadb, 
CREATE TABLE `play_tab_reco_content_intervene` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `position` int(4) NOT NULL COMMENT '',
  `title` varchar(512) NOT NULL COMMENT '',
  `desc` text COMMENT '描述',
  `type` int(2) NOT NULL COMMENT '',
  `mid` varchar(512) DEFAULT NULL COMMENT '',
  `cid` varchar(512) DEFAULT NULL COMMENT '',
  `appid` varchar(512) DEFAULT NULL COMMENT '',
  `operator` varchar(128) NOT NULL COMMENT '操作人',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '该条配置的更新时间',
  `start_time` int(13) NOT NULL COMMENT '开始时间/秒，时间戳',
  `end_time` int(13) NOT NULL COMMENT '结束时间/秒，时间戳',
  `status` int(2) NOT NULL COMMENT '状态',
  PRIMARY KEY (`id`)

**Comment by lance6716** [comment]
which version of MariaDB？

**Comment by zhoukangch** [comment]
10.0.10

**Comment by lance6716** [comment]
I guess that version is too old, maybe MariaDB can't write a MySQL compatible binlog. We use this library in out project and we require version should be at least 10.1.2.

BTW, I started a 10.5.8 MariaDB and can't run simply run your SQL.

```sql
MariaDB [test]> insert into play_tab_reco_content_intervene values (819, 2, '', '11666 ä¸»æ¥¼ æ<9a><97>é»<91>æ<89><8b>æ¸¸äº®ç<9b>¸æ<9a>´é<9b>ªå<98><89>å¹´å<8d><8e>ï¼<8c>ç²¾é<9b><95>ç»<86>ç<90>¢ç<9a><84>3Aå¤§ä½<9c>', 2, '', '116663', '54217670', 'touchliu', 1654741895, 1654741881, 1717900273, 1);
ERROR 1292 (22007): Incorrect datetime value: '1654741895' for column `test`.`play_tab_reco_content_intervene`.`update_time` at row 1
```

**Comment by zhoukangch** [comment]
![image](https://user-images.githubusercontent.com/38311280/172777360-ce5765dc-5a45-4c86-a4a3-9ed40256cdd9.png)

**Comment by zhoukangch** [comment]
Is this length variable particularly large?

**Comment by lance6716** [comment]
> Is this length variable particularly large?

I can't reproduce your issue, so only you can check the binlog content to know why `length` is wrong. You can refer to https://mariadb.com/kb/en/rows_event_v1v2/#mysql_type_blob-and-other-blob-types for encoding details.

**Comment by lance6716** [comment]
> > can you provide some steps to let us reproduce it?
> 
> '/_!_/;
> 
> ### INSERT INTO `png_cms_v8`.`play_tab_reco_content_intervene`
> ### SET
> ### @1=819 /* INT meta=0 nullable=0 is_null=0 */
> ### @2=2 /* INT meta=0 nullable=0 is_null=0 */
> ### @3='' /* VARSTRING(2048) meta=2048 nullable=0 is_null=0 */
> ### @4='11666 ä¸»æ¥¼ æ<9a><97>é»<91>æ<89><8b>æ¸¸äº®ç<9b>¸æ<9a>´é<9b>ªå<98><89>å¹´å<8d><8e>ï¼<8c>ç²¾é<9b><95>ç»<86>ç<90>¢ç<9a><84>3Aå¤§ä½<9c>' /* BLOB/TEXT meta=2 nullable=1 is_null=0 */
> ### @5=2 /* INT meta=0 nullable=0 is_null=0 */
> ### @6='' /* VARSTRING(2048) meta=2048 nullable=1 is_null=0 */
> ### @7='116663' /* VARSTRING(2048) meta=2048 nullable=1 is_null=0 */
> ### @8='54217670' /* VARSTRING(2048) meta=2048 nullable=1 is_null=0 */
> ### @9='touchliu' /* VARSTRING(512) meta=512 nullable=0 is_null=0 */
> ### @10=1654741895 /* TIMESTAMP meta=0 nullable=0 is_null=0 */
> ### @11=1654741881 /* INT meta=0 nullable=0 is_null=0 */
> ### @12=1717900273 /* INT meta=0 nullable=0 is_null=0 */
> ### @13=1 /* INT meta=0 nullable=0 is_null=0 */
> # at 81376240
> #220609 10:31:37 server id 638346941 end_log_pos 81376267 Xid = 175000658576 COMMIT/_!_/;

hi, is this content decoded by MariaDB's mysqlbinlog? if so, can you try MySQL's official mysqlbinlog? I think official mysqlbinlog also can't decode it.

**Comment by zhoukangch** [comment]
I seem to have found the reason, the 10.0.10 version of mariadb, the datetime field type only uses 7 bytes? But the canal is processed by 8 bytes, resulting in a misalignment

**Comment by zhoukangch** [comment]
datetime(3) cause it

**Comment by zhoukangch** [comment]
![image](https://user-images.githubusercontent.com/38311280/172978477-300b8035-1bd5-4128-9263-96c4093eaf61.png)

**Comment by lance6716** [comment]
Thanks, now I remember it's a bug of MariaDB https://jira.mariadb.org/browse/MDEV-5377 . Fix version is 10.1.2.

**Comment by zhoukangch** [comment]
get. thx,

**Comment by lance6716** [comment]
No I don't want to have many special logic to workaround bugs that breaks protocol.
