### ISSUE TITLE
Is this code supposed to work?

### ISSUE THREAD

**Issue by viciious** [go-mysql-org/go-mysql#705]
https://github.com/go-mysql-org/go-mysql/blob/master/client/conn.go#L87

`c.tlsConfig` can't be anything but nil at that point since the options array hasn't been applied to the connection yet

**Comment by lance6716** [comment]
You are right :sob: would you like to fix it?

**Comment by viciious** [comment]
Sure, but what would you suggest as the better approach? I suppose someone may rely on c.Conn being non-nil before the options are applied in order to set the initial Sequence.

**Comment by viciious** [comment]
Something like this maybe? #706
