### ISSUE TITLE
Feature: Set collation method alongside charset

### ISSUE THREAD

**Issue by gwvandesteeg** [go-mysql-org/go-mysql#727]
When creating a connection to the DB you also want to frequently ensure the correct collation method is used in addition to the character set.

ie. 
`SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci`
vs.
`SET NAMES utf8mb4 COLLATE utf8mb4_general_ci`
etc.

**Comment by lance6716** [comment]
Seems SQL driver can do it

https://github.com/go-sql-driver/mysql#collation

**Comment by gwvandesteeg** [comment]
Noticed it in the code for this project, pretty sure other SQL drivers handle it correctly.  It's a running issue with people assuming defaults for connections and drivers are sane (they're not.. go's http.Client is a good example). Especially when it comes to character sets and collations for SQL connections (never mind the fun with mariadb vs mysql).  So if I see one where it's incorrect, it gets mentioned and left for people to find and see if it's been fixed if they run into the same problem.  Sadly I don't often have the time to send in a PR to fix it myself.

**Comment by dveeden** [comment]
I think this has been implemented since this issue was filed.

See https://github.com/go-mysql-org/go-mysql?tab=readme-ov-file#collation and the PRs mentioning "collation".

@lance6716 @atercattus If any of you agree than we can close this
