### ISSUE TITLE
Misusing of defer

### ISSUE THREAD

**Issue by shizhx** [go-mysql-org/go-mysql#728]
https://github.com/go-mysql-org/go-mysql/blob/1c55c36dc919cb9cf7971359e2e185940dd17d2c/packet/conn.go#L90-L112

`defer utils.BytesBufferPut(buf)` and
```go
 		// if read block is big, do not cache buf any more 
 		if readSize > utils.TooBigBlockSize { 
 			buf = nil 
 		} 
```

`defer` capture `buf` early, so modify `buf` after `defer` not working.

**Comment by lance6716** [comment]
The reason is

> if read block is big, do not cache buf any more

Do you meet some problem with this feature?

**Comment by shizhx** [comment]
@lance6716 I mean set `buf = nil` has no effects after `defer utils.BytesBufferPut(buf)`.

**Comment by lance6716** [comment]
Oh thanks for pointing it out. `utils.BytesBufferPut` should be able to handle too large `buf`. 

Can you open a PR to fix it? I'll check it when review your PR.

**Comment by shizhx** [comment]
> Oh thanks for pointing it out. `utils.BytesBufferPut` should be able to handle too large `buf`.
> 
> Can you open a PR to fix it? I'll check it carefully when review your PR.

I read the `utils.BytesBufferPut` implementation, it has handled big buffer:
https://github.com/go-mysql-org/go-mysql/blob/master/utils/bytes_buffer_pool.go#L26-L30

so `buf = nil` has no effect, but 'not cache big buffer' function works as expected.

**Comment by skoef** [comment]
@shizhx thank you for pointing this out and opening a PR!

May I point out to you that this project is mainly, if not completely, run by volunteers, as do many open source projects. If you want something done, you should really adjust your tone of voice. Calling an honest mistake by a previous contributor "stupid" is certainly not constructive.

**Comment by shizhx** [comment]
@skoef I am very sorry, I will pay attention in the future.

**Comment by shizhx** [comment]
@skoef But this project is the most important library about MySQL replication, **yet the unit tests are too few**, some commits change same line repeatly to fix some 'stupid' issue. So I expect:
1. more unit tests.
2. more carefully review of commit.

**Comment by skoef** [comment]
@shizhx thank you for understanding! I agree that more unit testing is better and I encourage you to contribute as you seem to be engaged in the project!
