### ISSUE TITLE
which version of this repo support MySql 8.X

### ISSUE THREAD

**Issue by elliotchenzichang** [go-mysql-org/go-mysql#747]
hi, want to ask which version of this repo supports Mysql 8.X binlog replication protocol.

**Comment by elliotchenzichang** [comment]
Got this, but Canal can sync data from a MySql 8. X instance, right?

**Comment by dveeden** [comment]
I think we now support 8.0 and support for 8.4 is making good progress.

See also #866 

Please open a new issue if there is anything missing in support for MySQL 8.0.x
