### ISSUE TITLE
pool.GetConn nil pointer

### ISSUE THREAD

**Issue by zong400** [go-mysql-org/go-mysql#771]
程序跑一段时间之后崩了

```
func doExpTask(taskChan chan *Task, queryChan chan InsResult, wg *sync.WaitGroup) {
	defer wg.Done()
	for task := range taskChan {
		expTable(task, queryChan)
	}
}

func expTable(task *Task, queryChan chan InsResult) {
	pool := poolMap[task.Src.Schema]
	conn, e := pool.GetConn(context.Background())
	if e != nil {
		// panic(e.Error())
		logger.Panicln(e.Error())
	}
	defer pool.PutConn(conn)

	sql := selectSQL(task.Src.Table, &task.Src.Condition)

	var result mysql.Result
	var items []*Insitem
	conn.SetCharset("utf8mb4")
	conn.SetReadDeadline(time.Now().Add(5 * time.Second))
	conn.UseDB(task.Src.Schema)
        ......
```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x5e5448]

goroutine 57 [running]:
github.com/go-mysql-org/go-mysql/client.(*Pool).getConnection(0x0, {0x6f9c10, 0xc0000a0000})
        /data/gowork/pkg/mod/github.com/go-mysql-org/go-mysql@v1.7.0/client/pool.go:197 +0x48
github.com/go-mysql-org/go-mysql/client.(*Pool).GetConn(0x0, {0x6f9c10, 0xc0000a0000})
        /data/gowork/pkg/mod/github.com/go-mysql-org/go-mysql@v1.7.0/client/pool.go:146 +0x4c
main.expTable(0xc0005d0360, 0xc000202c60?)
        /data/gowork/src/mysqlsync/mysqlsync.go:289 +0x85
main.doExpTask(0x0?, 0x0?, 0x0?)
        /data/gowork/src/mysqlsync/mysqlsync.go:283 +0x7c
created by main.main.func1
        /data/gowork/src/mysqlsync/mysqlsync.go:101 +0x4d

**Comment by atercattus** [comment]
Hello.
I think a problem is in `pool := poolMap[task.Src.Schema]` line. You should check what `pool` is not nil.

**Comment by zong400** [comment]
@atercattus thanks,is my fault
