### ISSUE TITLE
how about add a builded docker image to make canal part more visibility and easier

### ISSUE THREAD

**Issue by elliotchenzichang** [go-mysql-org/go-mysql#784]
Hey there, I make a docker image that contains a ROW_format binlog, canal runner of this repo, and a based database building SQL. I want to make the canal demo run smoothly so that every user of the canal can run it easier to watch the binlog change of the executions they do.
For more details can refer to [this article](https://mp.weixin.qq.com/s/ANx2LVDM1sD0bwQg5JaGCA )

So, would you like to let me make a contribution to this repo?  Let this Docker image be a good example for running a canal instance. All I need to do is change the canal document part and use my docker image instead. Maybe I also can add all the code and files I mentioned in my article to the canal part of this repo.

**Comment by lance6716** [comment]
Thanks, I think you can create an repo for your project, like including the dockerfile to build the image. That's a more common way.

**Comment by elliotchenzichang** [comment]
Sure. Thanks.
