### ISSUE TITLE
How to close client pool ?

### ISSUE THREAD

**Issue by RainJoe** [go-mysql-org/go-mysql#794]
```go
import (
    "github.com/go-mysql-org/go-mysql/client"
)

pool := client.NewPool(log.Debugf, 100, 400, 5, "127.0.0.1:3306", `root`, ``, `test`)
// ...
conn, _ := pool.GetConn(ctx)
defer pool.PutConn(conn)

conn.Execute() / conn.Begin() / etc...
```
In some usecases, we want to close the pool and also close the underlying mysql connections to avoid resource leaks, but I didn't find a method like pool.Close to implement it.

**Comment by lance6716** [comment]
yes currently we don't have this feature. You can open a PR to implement it
