### ISSUE TITLE
什么情况下event.Rows长度会为0 或者为nil？

### ISSUE THREAD

**Issue by zhanghaiyang9999** [go-mysql-org/go-mysql#810]
使用下面的代码：
ev, err := streamer.GetEvent(contx)
event := ev.Event.(*replication.RowsEvent)
当ev.Header.EventType为replication.WRITE_ROWS_EVENTv1或者为 replication.WRITE_ROWS_EVENTv2时，正常情况下event.Rows会有值，但是测试过程中遇到过ev.Header.EventType为replication.WRITE_ROWS_EVENTv1或者为 replication.WRITE_ROWS_EVENTv2时,event.Rows的长度为0或者nil，不知道什么条件下会出现这种情况。

**Comment by lance6716** [comment]
duplicate with #811
