### ISSUE TITLE
canal.RowsEvent returns 2 duplicate rows for every update event

### ISSUE THREAD

**Issue by agorman** [go-mysql-org/go-mysql#815]
I'm trying to understand the case where the length of RowsEvent.Rows will be greater than 1. So for in my testing all of my insert and delete events have just one row. However, all of my update events have 2 identical rows.

If I update a single row in I get one RowsEvent with 2 Rows. If I update 2 rows then I get two RowsEvents each with 2 rows. The type is UpdateRowsEventV2.

Any idea what is going on? Should I be processing all rows in Rows or only the first?

mysql 5.7.42

Thanks!

**Comment by lance6716** [comment]
it should be the row content before and after the update. 

https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_binlog_row_image
searc for "each row change event contains two images"

**Comment by agorman** [comment]
Thank you! I totally missed that the data was different between the two returned rows.

Thank you for the link to the docs as well that clears everything up.
