### ISSUE TITLE
How to start binlog syncer from last position

### ISSUE THREAD

**Issue by ibroid** [go-mysql-org/go-mysql#832]
Hello, i try this library using an example from documentation

syncer := replication.NewBinlogSyncer(cfg)
streamer, _ := syncer.StartSync(mysql.Position{})
for {
	ev, _ := streamer.GetEvent(context.Background())
	ev.Dump(os.Stdout)
}

but i realize that sync is start from first binlog file. how i can start sync wiht the latest binlog file automatically ?

**Comment by minhtri1396** [comment]
I think you should listen on `OnPosSynced` method (the Canal package), and store the last received position in some place (ex: your database). So the program can use the saved position in `StartSync` method.

**Comment by samuelwoodcore** [comment]
can you expand further on this? @minhtri1396

**Comment by ibroid** [comment]
i was figured it out my self, heres the code
```
func StartEvent() {

	cfg := canal.NewDefaultConfig()
	cfg.Addr = os.Getenv("DB_SIPP_HOST")
	cfg.User = os.Getenv("DB_SIPP_USER")
	cfg.Password = os.Getenv("DB_SIPP_PASS")
	cfg.ServerID = 1
	cfg.IncludeTableRegex = []string{
		//any table here
	}

	cfg.Dump.ExecutionPath = ""

	c, err := canal.NewCanal(cfg)
	if err != nil {
		log.Log.Fatalln("Gagal new canal : ", err)
	}

	c.SetEventHandler(&MyEventHandler{})

	mp, _ := c.GetMasterPos()
	c.RunFrom(mp)
}
```
sorry i forgot to close the issue

**Comment by ibroid** [comment]
i was figured it out my self, heres the code
```
func StartEvent() {

	cfg := canal.NewDefaultConfig()
	cfg.Addr = os.Getenv("DB_SIPP_HOST")
	cfg.User = os.Getenv("DB_SIPP_USER")
	cfg.Password = os.Getenv("DB_SIPP_PASS")
	cfg.ServerID = 1
	cfg.IncludeTableRegex = []string{
		//any table here
	}

	cfg.Dump.ExecutionPath = ""

	c, err := canal.NewCanal(cfg)
	if err != nil {
		log.Log.Fatalln("Gagal new canal : ", err)
	}

	c.SetEventHandler(&MyEventHandler{})

	mp, _ := c.GetMasterPos()
	c.RunFrom(mp)
}
```
sorry i forgot to close the issue
