### ISSUE TITLE
Driver Compression Enablement

### ISSUE THREAD

**Issue by kvolmar** [go-mysql-org/go-mysql#859]
Is there a way to enable compression when using the Driver rather than the Client?

**Comment by kvolmar** [comment]
Specifically I've seen https://github.com/go-mysql-org/go-mysql/blob/7c31dc4e4e5bac6f8f9a73c04efad3e0af69e606/client/conn.go#L124-L128. Where is ccaps set and is there a way to configure them when using the Driver?

**Comment by lance6716** [comment]
> Specifically I've seen
> 
> https://github.com/go-mysql-org/go-mysql/blob/7c31dc4e4e5bac6f8f9a73c04efad3e0af69e606/client/conn.go#L124-L128
> 
> . Where is ccaps set and is there a way to configure them when using the Driver?

https://github.com/go-mysql-org/go-mysql/blob/7c31dc4e4e5bac6f8f9a73c04efad3e0af69e606/client/conn.go#L177-L180

**Comment by kvolmar** [comment]
I am currently using the go-sql-driver/mysql and interested in migrating to go-mysql-org/go-mysql specifically for the driver. I am evaluating the feasibility of using the database/sql library with your driver and enabling compression. I'm currently importing the driver with side effects and able to write to MySQL, but without compression. Are the compression settings configurable with env vars or in the DSN?

**Comment by lance6716** [comment]
Sorry I think this library does not have this way to configurate compression. Welcome to help us implement it, related files should be under `driver` folder.

**Comment by dvilaverde** [comment]
@kvolmar this has been implemented, can you close this issue?
