### ISSUE TITLE
Setting collations need adjustment

### ISSUE THREAD

**Issue by dveeden** [go-mysql-org/go-mysql#864]
Follow-up for #860

See also: 
- https://gitlab.com/wireshark/wireshark/-/merge_requests/15539
- https://bugs.mysql.com/bug.php?id=114818 / http://github.com/mysql/mysql-server/pull/541
- https://bugs.mysql.com/bug.php?id=114857 / http://github.com/mysql/mysql-connector-python/pull/96
- https://bugs.mysql.com/bug.php?id=114832

What is needed is that we set the collation in the handshake as 1 byte if the collation <=255 and that we send a `SET NAMES ... COLLATE ...` if the collation >255.

cc @lance6716  @dvilaverde

**Comment by dvilaverde** [comment]
I hope https://github.com/go-mysql-org/go-mysql/pull/865 addresses this issue.

**Comment by dveeden** [comment]
Thanks @dvilaverde !
