### ISSUE TITLE
Can I use this library to parse bytes to MySQL protocol?

### ISSUE THREAD

**Issue by tim-chow** [go-mysql-org/go-mysql#881]
I have already captured binary network packets using a packet capture tool like libpcap. Can I use this library to parse these byte sequences into the MySQL protocol?

**Comment by dveeden** [comment]
Not sure what you need or expect exactly. Either go-mysql or Wireshark might allow you to do this 

Is this for debugging? Do you want to extract rows and/or files from the dump?

**Comment by dveeden** [comment]
Closing that as there was no response
