### ISSUE TITLE
[canal] v1.9.1 lost ExecuteSelectStreaming 

### ISSUE THREAD

**Issue by zhujintao** [go-mysql-org/go-mysql#923]
v1.9.1 canal.go lost ```ExecuteSelectStreaming```
```
func (c *Canal) ExecuteSelectStreaming(cmd string, perRowCallback func(row []mysql.FieldValue) error, perResultCallback func(result *mysql.Result) error) (err error) {

```

**Comment by dveeden** [comment]
What version did still have `(*Canal).ExecuteSelectStreaming` ? I wasn't able to find any traces of this. I only found `(*Conn).ExecuteSelectStreaming`.
