### ISSUE TITLE
COM_BINLOG_DUMP_GTID.  parseBinlogDumpGTID  panic

### ISSUE THREAD

**Issue by goooooooooooooood** [go-mysql-org/go-mysql#924]
the data is come from mysql 5.7
	buf = []byte{
		0, 0, 139, 166, 51, 123, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 88, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 21, 68, 55, 139, 177, 143, 17, 237, 142, 55, 228, 61, 26, 94, 128, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 57, 71, 212, 82, 0, 0, 0, 0, 99, 24, 112, 68, 150, 11, 17, 237, 162, 244, 92, 111, 105, 46, 160, 132, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 189, 235, 27, 2, 0, 0, 0, 0,
	}

mysql can parse the data correctly, but parseBinlogDumpGTID will panic
 
command.go:
    gtidSet, err := parseBinlogDumpGTID(data) 

![image](https://github.com/user-attachments/assets/197b9a25-a6f9-4404-bec1-b1c223462aa1)

**Comment by goooooooooooooood** [comment]
func parseMysqlGtidDumpPacket(data []byte) (*mysql.MysqlGTIDSet, uint32, error) {
	var flags uint16
	var dataSize uint32
	var slaveServerID uint32
	var binlogFileNameSize uint32
	var binlogFileName string
	var binlogPos uint64

	var pos uint32
	flags = binary.LittleEndian.Uint16(data[pos:])
	pos += 2

	slaveServerID = binary.LittleEndian.Uint32(data[pos:])
	pos += 4

	binlogFileNameSize = binary.LittleEndian.Uint32(data[pos:])
	pos += 4

	binlogFileName = string(data[pos : pos+binlogFileNameSize])
	pos += binlogFileNameSize

	binlogPos = binary.LittleEndian.Uint64(data[pos:])
	pos += 8

	dataSize = binary.LittleEndian.Uint32(data[pos:])
	pos += 4

	//only support mysql gtid
	slaveGtidExecuted, err := mysql.DecodeMysqlGTIDSet(data[pos:])
	if err != nil {
		log.Errorf("DecodeMysqlGTIDSet error,err:%s,data:%v", err, data[pos:])
		return nil, 0, err
	}

	log.Debugf("handleBinlogDumpGtid:flag:%d,slaveServerID:%d,binlogFileNameSize:%d,"+
		"binlogFileName:%s,binlogPos:%d,dataSize:%d,slaveGtidExecuted:%v", flags, slaveServerID, binlogFileNameSize,
		binlogFileName, binlogPos, dataSize, *slaveGtidExecuted)
	return slaveGtidExecuted, slaveServerID, nil
}

**Comment by lance6716** [comment]
I see your screenshot, this is not the commit hash in our repo.

**Comment by goooooooooooooood** [comment]
Because I added logs

**Comment by lance6716** [comment]
> Because I added logs @lance6716

Please find that package (jedplus/go-mysql-org) and find
- which version of this package (go-mysql-org/go-mysql) does it use. (Maybe we have fixed the bug in later version?)
- produce a way to reproduce the problem

**Comment by goooooooooooooood** [comment]
@lance6716 
func parseBinlogDumpGTID(data []byte) (*mysql.MysqlGTIDSet, error) {
	if len(data) < 15 {
		return nil, mysql.ErrMalformPacket
	}
	lenPosName := binary.LittleEndian.Uint32(data[11:15])
	if len(data) < 22+int(lenPosName) {
		return nil, mysql.ErrMalformPacket
	}

	return mysql.DecodeMysqlGTIDSet(data[22+lenPosName:])
}

in v1.9.1    Slice index 11-15 seems wrong, I think it is 6-10

**Comment by lance6716** [comment]
Please provide a way to reproduce the problem using official MySQL binaries. I think the binlog content is not standard, is this a customized MySQL RDS that generate wrong binlog?

**Comment by dveeden** [comment]
It *might* help to do a network trace and load that in Wireshark to see how it decodes these bytes.
