### ISSUE TITLE
about oceanbase binlog support

### ISSUE THREAD

**Issue by yanming-zhang** [go-mysql-org/go-mysql#926]
After testing OceanBase, it was found that its binlog is not fully supported.

**Comment by dveeden** [comment]
I have near zero experience with OceanBase. What does the binlog in OB look like? Any docs on that? Is this just a feature request or do you intent to work on this and send a PR?

**Comment by yanming-zhang** [comment]
> I have near zero experience with OceanBase. What does the binlog in OB look like? Any docs on that? Is this just a feature request or do you intent to work on this and send a PR?

this is oceanbase website docs:
https://en.oceanbase.com/docs

**Comment by lance6716** [comment]
> > I have near zero experience with OceanBase. What does the binlog in OB look like? Any docs on that? Is this just a feature request or do you intent to work on this and send a PR?
> 
> this is oceanbase website docs: https://en.oceanbase.com/docs

This package supports MySQL binlog. Please ask Oceanbase to generate MySQL binlog to use this package.

**Comment by dveeden** [comment]
[This doc](https://en.oceanbase.com/docs/common-ocp-10000000001553977) says that they have MySQL compatible binlogs. So this *should* probably work. If not then they are probably less compatible than they say they are or I don't understand the architecture/topology of OB.

Please open a new issue if anything isn't working correctly that isn't a compatibility issue in OB. If you do so please include these:
- The full error message 
- Description for what you're trying to do 
- The code you're using (if possible)
- The version of all involved components
- A small binlog file

This can help us diagnose and reproduce the issue.

**Comment by yanming-zhang** [comment]
> [This doc](https://en.oceanbase.com/docs/common-ocp-10000000001553977) says that they have MySQL compatible binlogs. So this _should_ probably work. If not then they are probably less compatible than they say they are or I don't understand the architecture/topology of OB.
> 
> Please open a new issue if anything isn't working correctly that isn't a compatibility issue in OB. If you do so please include these:
> 
> * The full error message
> * Description for what you're trying to do
> * The code you're using (if possible)
> * The version of all involved components
> * A small binlog file
> 
> This can help us diagnose and reproduce the issue.

ok，thank you
