### ISSUE TITLE
use goInception parse oceanbase binlog

### ISSUE THREAD

**Issue by yanming-zhang** [go-mysql-org/go-mysql#927]
The tool I use is goInception, and the library it relies on is go-mysql. When I do the insert operation, it can not go to the following branch when parsing the oceanbase binlog:
https://github.com/hanchuanchuan/goInception/blob/master/session/parser.go#L338
![image](https://github.com/user-attachments/assets/c0b10994-d3dc-40dc-bbe0-bd66013696c2)

**Comment by yanming-zhang** [comment]
may be that these two event types are not supported

**Comment by dveeden** [comment]
As I said in https://github.com/go-mysql-org/go-mysql/issues/926#issuecomment-2437004778

> please include these:
> - The full error message

Not included
 
> - Description for what you're trying to do 

Included, thanks.

> - The code you're using (if possible)

Included, thanks.

> - The version of all involved components

Not included

> - A small binlog file

Not included


I think you should probably report this to https://github.com/hanchuanchuan/goInception instead and let them open a go-mysql issue if needed.

What go-mysql version do they include? Is it modified in any way?

What is the binlog content you're trying to parse?

**Comment by dveeden** [comment]
Looks like goInception is using a fork of an ancient version of go-mysql https://github.com/hanchuanchuan/goInception/blob/2f06c61b95d294b7b89d1e7bbaf039e97b04c41f/go.mod#L43

(Note that they also use percona/go-mysql, which isn't a fork of go-mysql)
